// gen_db_map.go
// Usage: go run gen_db_map.go
//
// Paths are resolved relative to this script file:
//   in:  ../database/types.go
//   out: ../database/schema.go
//
// Parses a Go source file containing PublicXxxSelect/Insert/Update structs
// and emits a Database > Public > Table mapped type hierarchy.

package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
	"text/template"
)

// tableEntry holds the resolved names for one table.
type tableEntry struct {
	TableName  string // e.g. "Organizations"
	StructName string // e.g. "OrganizationsTable"
	Select     string // e.g. "PublicOrganizationsSelect"
	Insert     string // e.g. "PublicOrganizationsInsert"
	Update     string // e.g. "PublicOrganizationsUpdate"
}

const outputTmpl = `// Code generated by ../internal/gen.go — DO NOT EDIT.

package {{.Package}}
{{range .Tables}}
type {{.StructName}} struct {
	Select {{.Select}}
	Insert {{.Insert}}
	Update {{.Update}}
}
{{end}}
type PublicSchema struct {
{{- range .Tables}}
	{{.TableName}} {{.StructName}}
{{- end}}
}

type Database struct {
	Public PublicSchema
}
`

func main() {
	// Resolve paths relative to this source file, so the script works
	// correctly regardless of the working directory it is invoked from.
	_, scriptFile, _, ok := runtime.Caller(0)
	if !ok {
		fmt.Fprintln(os.Stderr, "could not determine script file path")
		os.Exit(1)
	}
	scriptDir := filepath.Dir(scriptFile)

	inFile := filepath.Join(scriptDir, "..", "database", "types.go")
	outFile := filepath.Join(scriptDir, "..", "database", "schema.go")

	// --- Parse the source file ---
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, inFile, nil, 0)
	if err != nil {
		fmt.Fprintf(os.Stderr, "parse error: %v\n", err)
		os.Exit(1)
	}

	pkg := f.Name.Name

	// Collect all type names that match Public*{Select,Insert,Update}
	// Key: base name (e.g. "PublicOrganizations"), Value: set of suffixes found
	type suffixSet struct {
		hasSelect, hasInsert, hasUpdate bool
	}
	bases := map[string]*suffixSet{}

	for _, decl := range f.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.TYPE {
			continue
		}
		for _, spec := range genDecl.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			name := ts.Name.Name
			if !strings.HasPrefix(name, "Public") {
				continue
			}
			switch {
			case strings.HasSuffix(name, "Select"):
				base := strings.TrimSuffix(name, "Select")
				if bases[base] == nil {
					bases[base] = &suffixSet{}
				}
				bases[base].hasSelect = true
			case strings.HasSuffix(name, "Insert"):
				base := strings.TrimSuffix(name, "Insert")
				if bases[base] == nil {
					bases[base] = &suffixSet{}
				}
				bases[base].hasInsert = true
			case strings.HasSuffix(name, "Update"):
				base := strings.TrimSuffix(name, "Update")
				if bases[base] == nil {
					bases[base] = &suffixSet{}
				}
				bases[base].hasUpdate = true
			}
		}
	}

	// Only include bases that have all three operations
	var entries []tableEntry
	for base, s := range bases {
		if !s.hasSelect || !s.hasInsert || !s.hasUpdate {
			fmt.Fprintf(os.Stderr, "warning: %s is missing Select/Insert/Update — skipping\n", base)
			continue
		}
		// base = "PublicOrganizations" → tableName = "Organizations"
		tableName := strings.TrimPrefix(base, "Public")
		entries = append(entries, tableEntry{
			TableName:  tableName,
			StructName: tableName + "Table",
			Select:     base + "Select",
			Insert:     base + "Insert",
			Update:     base + "Update",
		})
	}

	// Sort deterministically
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].TableName < entries[j].TableName
	})

	// --- Render template ---
	tmpl, err := template.New("db_map").Parse(outputTmpl)
	if err != nil {
		fmt.Fprintf(os.Stderr, "template error: %v\n", err)
		os.Exit(1)
	}

	out, err := os.Create(outFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "could not create output file: %v\n", err)
		os.Exit(1)
	}
	defer out.Close()

	data := struct {
		Package string
		Tables  []tableEntry
	}{
		Package: pkg,
		Tables:  entries,
	}

	if err := tmpl.Execute(out, data); err != nil {
		fmt.Fprintf(os.Stderr, "template execution error: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("✓ wrote %d table entries to %s\n", len(entries), outFile)
}