// Code generated by ../internal/gen.go — DO NOT EDIT.

package database

type ClientsTable struct {
	Select PublicClientsSelect
	Insert PublicClientsInsert
	Update PublicClientsUpdate
}

type ClientsProjectsTable struct {
	Select PublicClientsProjectsSelect
	Insert PublicClientsProjectsInsert
	Update PublicClientsProjectsUpdate
}

type FavoritesTable struct {
	Select PublicFavoritesSelect
	Insert PublicFavoritesInsert
	Update PublicFavoritesUpdate
}

type FilesTable struct {
	Select PublicFilesSelect
	Insert PublicFilesInsert
	Update PublicFilesUpdate
}

type FilesVersionsTable struct {
	Select PublicFilesVersionsSelect
	Insert PublicFilesVersionsInsert
	Update PublicFilesVersionsUpdate
}

type FoldersTable struct {
	Select PublicFoldersSelect
	Insert PublicFoldersInsert
	Update PublicFoldersUpdate
}

type MembersTable struct {
	Select PublicMembersSelect
	Insert PublicMembersInsert
	Update PublicMembersUpdate
}

type OrganizationsTable struct {
	Select PublicOrganizationsSelect
	Insert PublicOrganizationsInsert
	Update PublicOrganizationsUpdate
}

type PermissionsTable struct {
	Select PublicPermissionsSelect
	Insert PublicPermissionsInsert
	Update PublicPermissionsUpdate
}

type ProfilesTable struct {
	Select PublicProfilesSelect
	Insert PublicProfilesInsert
	Update PublicProfilesUpdate
}

type ProjectsTable struct {
	Select PublicProjectsSelect
	Insert PublicProjectsInsert
	Update PublicProjectsUpdate
}

type StorageProvidersTable struct {
	Select PublicStorageProvidersSelect
	Insert PublicStorageProvidersInsert
	Update PublicStorageProvidersUpdate
}

type StorageUploadsTable struct {
	Select PublicStorageUploadsSelect
	Insert PublicStorageUploadsInsert
	Update PublicStorageUploadsUpdate
}

type PublicSchema struct {
	Clients ClientsTable
	ClientsProjects ClientsProjectsTable
	Favorites FavoritesTable
	Files FilesTable
	FilesVersions FilesVersionsTable
	Folders FoldersTable
	Members MembersTable
	Organizations OrganizationsTable
	Permissions PermissionsTable
	Profiles ProfilesTable
	Projects ProjectsTable
	StorageProviders StorageProvidersTable
	StorageUploads StorageUploadsTable
}

type Database struct {
	Public PublicSchema
}
