do
$$
    declare
        _uid uuid := gen_random_uuid(); -- for security, always generate custom ID
    begin
        insert into auth.users ("instance_id",
                                "id",
                                "aud",
                                "role",
                                "email",
                                "encrypted_password",
                                "email_confirmed_at",
                                "invited_at",
                                "confirmation_token",
                                "confirmation_sent_at",
                                "recovery_token",
                                "recovery_sent_at",
                                "email_change_token_new",
                                "email_change",
                                "email_change_sent_at",
                                "last_sign_in_at",
                                "raw_app_meta_data",
                                "raw_user_meta_data",
                                "is_super_admin",
                                "created_at",
                                "updated_at",
                                "phone",
                                "phone_confirmed_at",
                                "phone_change",
                                "phone_change_token",
                                "phone_change_sent_at",
                                "email_change_token_current",
                                "email_change_confirm_status",
                                "banned_until",
                                "reauthentication_token",
                                "reauthentication_sent_at",
                                "is_sso_user",
                                "deleted_at",
                                "is_anonymous")
        values ('00000000-0000-0000-0000-000000000000',
                _uid,
                'admin',
                'admin',
                'admin@localhost',
                extensions.crypt(gen_random_uuid()::text, extensions.gen_salt('bf', 12)),
                current_timestamp,
                null,
                '',
                null,
                '',
                null,
                '',
                '',
                null,
                null,
                '{
                  "provider": "email",
                  "providers": [
                    "email"
                  ]
                }',
                '{
                  "email_verified": true,
                  "full_name": "Administrator"
                }',
                null,
                current_timestamp,
                current_timestamp,
                null,
                null,
                '',
                '',
                null,
                '',
                0,
                null,
                '',
                null,
                false,
                null,
                false);

        insert into auth.identities ("provider_id",
                                     "user_id",
                                     "identity_data",
                                     "provider",
                                     "last_sign_in_at",
                                     "created_at",
                                     "updated_at",
                                     "id")
        values (_uid,
                _uid,
                jsonb_build_object(
                        'sub', _uid,
                        'email', 'admin@localhost',
                        'email_verified', false,
                        'phone_verified', false
                ),
                'email',
                current_timestamp,
                current_timestamp,
                current_timestamp,
                gen_random_uuid());
    end;
$$;
